version: '3.9'

services:
  api:
    build: .
    command: gunicorn --reload -b 0.0.0.0:5000 app:api
    volumes:
       - .:/src/app
    ports:
       - "5000:5000"
    links:
       - db
       - redis
    environment:
       DEBUG: "True"
       SECRET_KEY: ubersecretkey
  db:
    image: postgres
    restart: always
    ports:
       - "5432:5432"
    environment:
       POSTGRES_DB: sass-db
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: password01
  redis:
    image: redis
    ports:
       - "6379:6379"
  worker:
    build: .
    command: celery worker -B -l info -A somesaas.celery.tasks
    links:
       - redis 
       - db
       - api

volumes:
  redis: {}