version: '3.9'

services:
  api:
    build: .
    image: api
    command: gunicorn --reload -b 0.0.0.0:5000 api:api --log-level debug
    volumes:
      - .:/src/app
    ports:
      - "5000:5000"
    links:
      - db
      - redis
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
      SECRET_KEY: ${SECRET_KEY}
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  worker:
    image: api
    command: celery -A tasks worker --loglevel=INFO --logfile=logs/celery.log
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
    depends_on:
      - redis 
      - api
    volumes:
      - .:/src/app
      - ./logs:/src/app/logs
  monitor:
    image: api
    ports:
      - "5555:5555"
    command:  flower -A tasks --port=5555 --broker=${CELERY_BROKER}
    depends_on:
      - api
      - redis

volumes:
  redis: {}