version: '3.9'

services:
  api:
    build: .
    image: api
    container_name: ${API_HOSTNAME}
    command: sh -c "cd /src && alembic upgrade head && cd app && gunicorn --reload -b 0.0.0.0:5000 api:api --log-level debug"
    volumes:
      - ./app:/src/app
      - ./alembic:/src/alembic
      - ./alembic.ini:/src/alembic.ini
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
      RATE_LIMIT_PER_MINUTE: ${RATE_LIMIT_PER_MINUTE:-30}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
  db:
    image: postgres
    restart: always
    container_name: ${POSTGRES_HOSTNAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis
    container_name: ${BROKER_HOSTNAME}
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  worker:
    image: api
    container_name: ${CELERY_HOSTNAME}
    command: celery -A tasks worker --loglevel=INFO --logfile=../logs/celery.log
    env_file:
      - .env
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
    depends_on:
      - redis
      - db
      - api
    volumes:
      - ./app:/src/app
      - ./logs:/src/logs
  monitor:
    image: api
    container_name: ${MONITOR_HOSTNAME}
    ports:
      - "5555:5555"
    command: flower -A tasks --port=5555 --broker=${CELERY_BROKER}
    env_file:
      - .env
    depends_on:
      - api
      - redis

volumes:
  redis: {}
